//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_Heating.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address_List_View
    {
        public int ID_Вулиці { get; set; }
        public string Назва_вулиці { get; set; }
        public string Район { get; set; }
        public string C__Будинку { get; set; }
        public string C__Квартири { get; set; }
        public string C__Офісу { get; set; }
        public string Тип_будівлі { get; set; }
        public string Назва_закладу { get; set; }
    }
}
