//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_Heating.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicators_List_View
    {
        public System.DateTime Дата_та_час { get; set; }
        public int ID_сенсору { get; set; }
        public string Тип_датчика { get; set; }
        public string Показник { get; set; }
        public string Назва_вулиці { get; set; }
        public string Район { get; set; }
        public string C__Будинку { get; set; }
        public string C__Квартири { get; set; }
        public string C__Офісу { get; set; }
        public string Назва_закладу { get; set; }
        public int ID_адреси { get; set; }
        public int ID_вулиці { get; set; }
        public int ID_району { get; set; }
    }
}
