//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_heating.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance_check_StandartView
    {
        public int ID_Тех_роботи { get; set; }
        public string Прізвище_працівника { get; set; }
        public string Ім_я_працівника { get; set; }
        public string По_Батькові_працівника { get; set; }
        public System.DateTime Дата_народження { get; set; }
        public string Номер_телефону { get; set; }
        public string Резервний_номер_телефону { get; set; }
        public string Тип_роботи { get; set; }
        public string Статус { get; set; }
        public string Дата_початку_робіт { get; set; }
        public string Дата_закінчення_робіт { get; set; }
    }
}
