//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_heating.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMS_check_AdminView
    {
        public int User_ID { get; set; }
        public string Логін { get; set; }
        public int ОМС_User_ID { get; set; }
        public string Прізвище { get; set; }
        public string Ім_я { get; set; }
        public string По_Батькові { get; set; }
        public string Стать { get; set; }
        public System.DateTime Дата_народження { get; set; }
        public string Номер_телефону { get; set; }
        public string Резервний_номер_телефону { get; set; }
        public string Назва_вулиці { get; set; }
        public string Район { get; set; }
        public string Номер_будинку { get; set; }
    }
}
