//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_heating.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sensor_list_View
    {
        public int ID { get; set; }
        public string Тип_датчика { get; set; }
        public string Назва_вулиці { get; set; }
        public string Район { get; set; }
        public string Номер_будинку { get; set; }
        public string Номер_квартири { get; set; }
        public string Номер_офісу { get; set; }
        public string Назва_закладу { get; set; }
    }
}
