//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_Heating.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_List_View
    {
        public int ID_Користувача { get; set; }
        public string Логін { get; set; }
        public string Роль_у_системі { get; set; }
        public string Прізвище { get; set; }
        public string Ім_я { get; set; }
        public string По_Батькові { get; set; }
        public string Стать { get; set; }
        public System.DateTime Дата_народження { get; set; }
        public string Н_р_телефону { get; set; }
        public string Резервний_н_р_телефону { get; set; }
        public string Назва_вулиці { get; set; }
        public string C__Будинку { get; set; }
        public string C__Квартири { get; set; }
        public string C__Офісу { get; set; }
        public string Район { get; set; }
        public string Тип_будинку { get; set; }
        public string Назва_закладу { get; set; }
        public string ID_адреси { get; set; }
        public string ID_вулиці { get; set; }
        public string ID_району { get; set; }
    }
}
